Ci 1008 seo add a breadcrumb list to article json ld metadata
Financial-Times/next-json-ld pull request #43
Opened 2022-05-04 10:21 UTC by juanSanchezAlcala

Why ?
There is a recommendation to improve SEO that we should set a breadcrumb ld+json script into every article. see [ticket](https://financialtimes.atlassian.net/browse/CI-1008)
How?
Since we don't have a breadcrumb we are going to build or breadcrumb for SEO in the next way:

-We will search in annotations all items with "implicitAbout" and "about" items. The order of preference is "implicitAbout" go first, in case a conflict we will pick those who have less slashes in their relativeUrl , in case of conflict with predicate and slashes we will pick in alphabetical order the prefLabel. The prefLabel will be the name used to build the breadcrumb. 
-If the item has a displayConcept property this annotation will be set as the last item of the breadcrumb
-The breadcrumb will have a maximum of 3 items

Using this approach the breadcrumb will remain the same even if the order of annotations change trying to have sense in order of the information that we can gather from annotations.

I attach a report in json and csv format with info of the articles and their breadcrumb ld+json. This report was generated with "puppeteer" navigating throw pages, so it could be reply easily in any change.

[log.csv](https://github.com/Financial-Times/next-json-ld/files/8619437/log.csv)
[log.json.txt](https://github.com/Financial-Times/next-json-ld/files/8619441/log.json.txt)

2022-05-04 14:54 UTC, juanSanchezAlcala commented
I've made an update on report files and code

2022-05-05 14:00 UTC, GlynnPhillips requested changes

2022-05-05 14:00 UTC, GlynnPhillips commented on types/breadcrumb.js
> +	let items = getBreadcrumbItemsFromAnnotation(content.annotations);
**Suggestion:** I would prefer this to be reworked into a `const`. The problem I have with a `let` is that I now need to keep a mental model of what this could change into at any stage. Using `const` means I can better understand what each value will be at any stage in its lifecycle

2022-05-05 14:00 UTC, GlynnPhillips commented on types/breadcrumb.js
> +	}).filter(annotation => Object.keys(predicateWeights).includes(annotation.predicateName)).sort(comparePredicates)
**Suggestion:** There is a lot happening here and it is therefore difficult to understand each part. I think we could optimize this better for readability and future maintenance. Maybe something like this would be better



```js
const highlLevelAnnotations = annotations
    .filter(annotation => predicateWeights[annotation.predicateName]
);
const orderedAnnotations = highlLevelAnnotations.sort(orderByWeighting);

```

2022-05-05 14:00 UTC, GlynnPhillips commented on types/breadcrumb.js
> +function countSlashes (str){
**Suggestion:** To prevent confusion please use verbose naming `string`

2022-05-05 14:00 UTC, GlynnPhillips commented on types/breadcrumb.js
> +	return (str.match(/\//g) || []).length;
**Suggestion:** I know this is a simple one but I always try to avoid regex where possible. Maybe using split would be nicer to read it would also mean you don't need the `||` as split will always return us an array.


```js
return str.split('/').length - 1;
```

2022-05-05 15:20 UTC, juanSanchezAlcala commented on types/breadcrumb.js
> +	return items;
> **Suggestion:** I found this section very difficult to follow and I had to run it to understand what is happening. I think this could be simplified to prioritise readability.
> 
> It would also be nicer to understand if there was less mutation happening to the array and we were explicit about when we are creating a new array with different values.

Here what im doing is check if inside "items" exists "lastItem" and if it exists delete because we need to set it into the last position and have a maximum of 3 items . Maybe sometimes we don't have "lastItem" because it comes from displayConcept property and maybe this property do not exists always so we pick the three elements from annotations . Due to this we need to recalculate the position of each element because we need to set position right. 

I'll try to find a way easier to do it but maybe i do not find a good way to do with a "items" as a const. Let me review and I'll notice you

2022-05-06 07:58 UTC, juanSanchezAlcala commented
I think i've almost solved all the issues you appoint in the code . I refactored the code to be more understandable and when it posible use const , also i have added more tests. Can you review it again ?

2022-05-10 12:43 UTC, GlynnPhillips requested changes
Couple of small suggestions

2022-05-10 12:43 UTC, GlynnPhillips commented on types/breadcrumb.js
> +		return getBreadcrumbItem(index + 1,annotation.prefLabel,annotation.url);
**Suggestion:** It would be great go set `index + 1` as a named variable so its clear what this is being used for without needing to look at the function that receives it.

```js
const position = index + 1;
```

2022-05-10 12:43 UTC, GlynnPhillips commented on types/breadcrumb.js
> +}
**Suggestion:** I feel like this function is an unnecessary abstraction and could be be put into the `getHierarchyAnnotations` function

```js
function getHierarchyAnnotations (annotations) {
	if (!annotations || (annotations && !annotations.length)) {
             return [];
        }
	const highlLevelAnnotations = annotations.map(annotation => {
		annotation.predicateName = annotation.predicate.split('/').pop();
		return annotation;
	}).filter(annotation => predicateWeights[annotation.predicateName]);

	return highlLevelAnnotations.sort(orderByPredicateName).slice(0,maxTagNumber);
}
```

2022-05-10 14:41 UTC, juanSanchezAlcala commented
Yes you are right , I've just made the changes.

2022-05-12 12:28 UTC, GlynnPhillips approved these changes

2022-05-12 13:52 UTC, merged